name: Tag Commit for Release

on:
  workflow_dispatch:

jobs:
  push_tag:
    name: Push version tag
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      should_call_release: ${{ steps.release_trigger.outputs.should_call_release }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUBLISH_PAT || secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Extract version from source
        id: extract_version
        run: |
          version_name=$(./gradlew -q :app:version | jq -r .versionName)
          echo "version=v$version_name" >> $GITHUB_OUTPUT

      - name: Tag current commit and push
        run: |
          git tag -f "${{ steps.extract_version.outputs.version }}"
          git push -f origin "${{ steps.extract_version.outputs.version }}"

      - name: Determine release trigger
        id: release_trigger
        run: echo "should_call_release=$IS_PAT_MISSING" >> $GITHUB_OUTPUT
        env:
          IS_PAT_MISSING: ${{ secrets.PUBLISH_PAT == '' }}

  call_release_workflow:
    name: Release workflow
    if: "needs.push_tag.outputs.should_call_release == 'true'"
    needs: push_tag
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.push_tag.outputs.version }}
    secrets: inherit
