name: Test

on:
  pull_request:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/README*.md'
      - '**/BUILDING.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: "-Dorg.gradle.project.kotlin.compiler.execution.strategy=in-process"

    steps:
      - uses: actions/checkout@v4

      - name: Free up disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew build --no-daemon

      - name: Archive reports for failed tests
        if: "failure()"
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '*/build/reports'
